[theme]
primaryColor="#00f2ff"
backgroundColor="#0a0a0a"
secondaryBackgroundColor="#1a1a1a"
textColor="#ffffff"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
